## 01 Import Libraries 

In [2]:
# Data Anlaysis
import pandas as pd
import numpy as np
import os
# Visualization
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
# Machine Learning Algorithms
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
# Display graphs without calling them specifically
%matplotlib inline

## 02 Import Data

In [4]:
path = r'D:\Data Analyst\Task 6.1\Housing price'

In [5]:
df = pd.read_csv(os.path.join(path, 'df_new.csv'), index_col = 0)
df_SalePrice = pd.read_csv(os.path.join(path, 'SalePrice for regression.csv'), index_col = 0)

In [6]:
# Check the imported dataset
df.head()

GrLivArea  GarageCars  TotalBsmtSF  FullBath  Log_Price  MSSubClass  \
0       1710         2.0        856.0         2  12.247699           5   
1       1262         2.0       1262.0         2  12.109016           0   
2       1786         2.0        920.0         2  12.317171           5   
3       1717         3.0        756.0         1  11.849405           6   
4       2198         3.0       1145.0         2  12.429220           5   

   MSZoning  LotShape  Neighborhood  BldgType  ...  BsmtQual  BsmtExposure  \
0         3         3             5         0  ...         2             4   
1         3         3            24         0  ...         2             1   
2         3         0             5         0  ...         2             2   
3         3         0             6         0  ...         4             4   
4         3         0            15         0  ...         2             0   

   BsmtFinType1  HeatingQC  KitchenQual  PavedDrive  SaleType  SaleCondition  \
0             2          0            2           2         8              4   
1             0          0            3           2         8              4   
2             2          0            2           2         8              4   
3             0          2            2           2         8              0   
4             2          0            2           2         8              4   

   Age  RenovateAge  
0    7            0  
1   34            0  
2    9            1  
3   95           55  
4   10            0  

[5 rows x 28 columns]

In [7]:
df.isnull().sum()

GrLivArea           0
GarageCars          0
TotalBsmtSF         0
FullBath            0
Log_Price        1435
MSSubClass          0
MSZoning            0
LotShape            0
Neighborhood        0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
RoofStyle           0
Exterior2nd         0
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual            0
BsmtExposure        0
BsmtFinType1        0
HeatingQC           0
KitchenQual         0
PavedDrive          0
SaleType            0
SaleCondition       0
Age                 0
RenovateAge         0
dtype: int64

In [8]:
df.shape

(2872, 28)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2872 entries, 0 to 2872
Data columns (total 28 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   GrLivArea      2872 non-null   int64  
 1   GarageCars     2872 non-null   float64
 2   TotalBsmtSF    2872 non-null   float64
 3   FullBath       2872 non-null   int64  
 4   Log_Price      1437 non-null   float64
 5   MSSubClass     2872 non-null   int64  
 6   MSZoning       2872 non-null   int64  
 7   LotShape       2872 non-null   int64  
 8   Neighborhood   2872 non-null   int64  
 9   BldgType       2872 non-null   int64  
 10  HouseStyle     2872 non-null   int64  
 11  OverallQual    2872 non-null   int64  
 12  OverallCond    2872 non-null   int64  
 13  RoofStyle      2872 non-null   int64  
 14  Exterior2nd    2872 non-null   int64  
 15  ExterQual      2872 non-null   int64  
 16  ExterCond      2872 non-null   int64  
 17  Foundation     2872 non-null   int64  
 18  BsmtQual

## 03 Feature Scaling

###### Split data into training and test data set 

In [10]:
# Set up test data set 
df_test = df[df['Log_Price'].isnull() == True]
df_test1 = df_test.drop(columns = ['Log_Price'], axis = 1)

In [11]:
pd.set_option('display.max_columns', None)
df_test1.head()

GrLivArea  GarageCars  TotalBsmtSF  FullBath  MSSubClass  MSZoning  \
1437        896         1.0        882.0         1           0         2   
1438       1329         1.0       1329.0         1           0         3   
1439       1629         2.0        928.0         2           5         3   
1440       1604         2.0        926.0         2           5         3   
1441       1280         2.0       1280.0         2          11         3   

      LotShape  Neighborhood  BldgType  HouseStyle  OverallQual  OverallCond  \
1437         3            12         0           2            4            5   
1438         0            12         0           2            5            5   
1439         0             8         0           5            4            4   
1440         0             8         0           5            5            5   
1441         0            22         4           2            7            4   

      RoofStyle  Exterior2nd  ExterQual  ExterCond  Foundation  BsmtQual  \
1437          1           13          3          4           1         4   
1438          3           14          3          4           1         4   
1439          1           13          3          4           2         2   
1440          1           13          3          4           2         4   
1441          1            6          2          4           2         2   

      BsmtExposure  BsmtFinType1  HeatingQC  KitchenQual  PavedDrive  \
1437             4             5          4            3           2   
1438             4             0          4            2           2   
1439             4             2          2            3           2   
1440             4             2          0            2           2   
1441             4             0          0            2           2   

      SaleType  SaleCondition  Age  RenovateAge  
1437         8              4   49            0  
1438         8              4   52            0  
1439         8              4   13            1  
1440         8              4   12            0  
1441         8              4   18            0

In [12]:
df_test1.shape

(1435, 27)

In [13]:
df_test1.isnull().sum()

GrLivArea        0
GarageCars       0
TotalBsmtSF      0
FullBath         0
MSSubClass       0
MSZoning         0
LotShape         0
Neighborhood     0
BldgType         0
HouseStyle       0
OverallQual      0
OverallCond      0
RoofStyle        0
Exterior2nd      0
ExterQual        0
ExterCond        0
Foundation       0
BsmtQual         0
BsmtExposure     0
BsmtFinType1     0
HeatingQC        0
KitchenQual      0
PavedDrive       0
SaleType         0
SaleCondition    0
Age              0
RenovateAge      0
dtype: int64

In [14]:
# Set up training data set 
df_train = df[df['Log_Price'].isnull() == False]

In [15]:
df_train.head()

GrLivArea  GarageCars  TotalBsmtSF  FullBath  Log_Price  MSSubClass  \
0       1710         2.0        856.0         2  12.247699           5   
1       1262         2.0       1262.0         2  12.109016           0   
2       1786         2.0        920.0         2  12.317171           5   
3       1717         3.0        756.0         1  11.849405           6   
4       2198         3.0       1145.0         2  12.429220           5   

   MSZoning  LotShape  Neighborhood  BldgType  HouseStyle  OverallQual  \
0         3         3             5         0           5            6   
1         3         3            24         0           2            5   
2         3         0             5         0           5            6   
3         3         0             6         0           5            6   
4         3         0            15         0           5            7   

   OverallCond  RoofStyle  Exterior2nd  ExterQual  ExterCond  Foundation  \
0            4          1           13          2          4           2   
1            7          1            8          3          4           1   
2            4          1           13          2          4           2   
3            4          1           15          3          4           0   
4            4          1           13          2          4           2   

   BsmtQual  BsmtExposure  BsmtFinType1  HeatingQC  KitchenQual  PavedDrive  \
0         2             4             2          0            2           2   
1         2             1             0          0            3           2   
2         2             2             2          0            2           2   
3         4             4             0          2            2           2   
4         2             0             2          0            2           2   

   SaleType  SaleCondition  Age  RenovateAge  
0         8              4    7            0  
1         8              4   34            0  
2         8              4    9            1  
3         8              0   95           55  
4         8              4   10            0

In [16]:
df_train.shape

(1437, 28)

In [17]:
# Prepare a dataset for training output
df_train_y = df_train[['Log_Price']]

In [18]:
df_train_y

Log_Price
0     12.247699
1     12.109016
2     12.317171
3     11.849405
4     12.429220
...         ...
1432  12.072547
1433  12.254868
1434  12.493133
1435  11.864469
1436  11.901590

[1437 rows x 1 columns]

In [19]:
# Prepare a dataset for training input
df_train_x = df_train.drop(columns = ['Log_Price'], inplace = False)

In [20]:
df_train_x.head()

GrLivArea  GarageCars  TotalBsmtSF  FullBath  MSSubClass  MSZoning  \
0       1710         2.0        856.0         2           5         3   
1       1262         2.0       1262.0         2           0         3   
2       1786         2.0        920.0         2           5         3   
3       1717         3.0        756.0         1           6         3   
4       2198         3.0       1145.0         2           5         3   

   LotShape  Neighborhood  BldgType  HouseStyle  OverallQual  OverallCond  \
0         3             5         0           5            6            4   
1         3            24         0           2            5            7   
2         0             5         0           5            6            4   
3         0             6         0           5            6            4   
4         0            15         0           5            7            4   

   RoofStyle  Exterior2nd  ExterQual  ExterCond  Foundation  BsmtQual  \
0          1           13          2          4           2         2   
1          1            8          3          4           1         2   
2          1           13          2          4           2         2   
3          1           15          3          4           0         4   
4          1           13          2          4           2         2   

   BsmtExposure  BsmtFinType1  HeatingQC  KitchenQual  PavedDrive  SaleType  \
0             4             2          0            2           2         8   
1             1             0          0            3           2         8   
2             2             2          0            2           2         8   
3             4             0          2            2           2         8   
4             0             2          0            2           2         8   

   SaleCondition  Age  RenovateAge  
0              4    7            0  
1              4   34            0  
2              4    9            1  
3              0   95           55  
4              4   10            0

In [21]:
# Split data into a training set and a test set

X_train, X_var, y_train, y_var = train_test_split(df_train_x, df_train_y, test_size = 0.3, random_state = 0) 

In [22]:
X_train.shape

(1005, 27)

In [23]:
X_var.shape

(432, 27)

In [24]:
y_train.shape

(1005, 1)

In [25]:
y_var.shape

(432, 1)

###### Regression Analysis

In [26]:
# Standardize features for training data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)

In [27]:
X_train_sc

array([[-1.44557638, -2.357158  , -0.62584129, ...,  0.20024589,
         1.56383152,  0.52459384],
       [-0.04292257, -0.99803936, -0.69240606, ...,  0.20024589,
        -0.18755062, -0.55432289],
       [ 0.30012879, -0.99803936, -0.76390155, ...,  0.20024589,
         0.96902249,  1.64500738],
       ...,
       [ 0.94969351, -2.357158  , -0.24124485, ..., -3.42582829,
         1.99341582,  1.06405221],
       [-1.2831852 , -0.99803936, -0.42861235, ..., -3.42582829,
         0.40725841, -0.55432289],
       [-0.70669652, -0.99803936, -0.14263038, ...,  0.20024589,
         0.63857303, -0.55432289]])

In [28]:
y_train

Log_Price
811   11.603689
1346  11.751950
459   11.894788
1354  11.418626
1222  12.323416
...         ...
763   11.877576
835   11.786770
1216  11.775297
559   11.695255
684   11.724005

[1005 rows x 1 columns]

In [29]:
# Create a regression object
regression = LinearRegression()

In [30]:
# Fit the regression object onto the training set

regression.fit(X_train_sc, y_train)

LinearRegression()

In [31]:
# Standardize features for test data (in training dataset)
X_var_sc = sc.transform(X_var)

In [32]:
# Predict the SalePrice for training dataset
y_train_predicted = regression.predict(X_var_sc)

In [34]:
# To merge actual SalePrice and predicted value into one dataframe, we need to have them in the same form at the beginning
y_actual_numpy = y_var.to_numpy()

In [36]:
# Settle actual SalePrice and predicted value into one dataframe to have a better view
data_actual_vs_prediction = pd.DataFrame({'Actual': y_actual_numpy.flatten(), 'Predicted': y_train_predicted.flatten()})

In [37]:
# We don't need the digits agfter decimal
pd.set_option("display.precision", 2)

In [38]:
data_actual_vs_prediction

Actual  Predicted
0     11.61      11.61
1     12.53      12.44
2     12.35      12.47
3     12.04      12.11
4     12.21      12.21
..      ...        ...
427   12.04      11.94
428   11.91      11.97
429   12.56      12.79
430   11.92      11.88
431   11.79      11.82

[432 rows x 2 columns]

From the table above, we can see that our prediction is close to the actual value but still with some value distance. How good have we predicted the SalePrice is difficult to know from the table directly, so we need Mean Sqaure Error and R2 score to help us anlayze the result. 

In [56]:
AP = np.exp(y_actual_numpy)
PP = np.exp(y_train_predicted)

In [69]:
# Mean squared error/ r2 score
rmse = mean_squared_error(AP, PP)
r2 = r2_score(AP, PP)

In [70]:
print('Mean squared error:', rmse)
print('R2 score:', r2)

Mean squared error: 652787748.2109582
R2 score: 0.9003408890443647


In [71]:
data_actual_vs_prediction.loc[:, 'Actual Price'] = AP
data_actual_vs_prediction.loc[:, 'Predicted Price'] = PP

In [72]:
data_actual_vs_prediction.head()

Actual  Predicted  Actual Price  Predicted Price
0   11.61      11.61      110001.0        110454.47
1   12.53      12.44      277501.0        253653.48
2   12.35      12.47      232001.0        260864.40
3   12.04      12.11      170001.0        181298.10
4   12.21      12.21      200625.0        201076.39

In [73]:
data_actual_vs_prediction.shape

(432, 4)

In [74]:
data_actual_vs_prediction_1 = data_actual_vs_prediction[(data_actual_vs_prediction['Actual Price'] < 500000)]

In [75]:
data_actual_vs_prediction_1.shape

(430, 4)

In [76]:
data_actual_vs_prediction_1['Actual Price'].describe()

count       430.00
mean     182581.62
std       73916.95
min       35312.00
25%      131001.00
50%      162701.00
75%      222001.00
max      475001.00
Name: Actual Price, dtype: float64

In [77]:
import math
math.sqrt(652787748)/475001

0.053788752675307284

We have small RMSE (5.3% max. price), which means the data points are close to our regression line. 

Moreover, we have R2 score 0.9. The larger the R2 score is (close to 1), the more precise is our prediction. It is obvious that we still need to improve the prediction model and reduce the error in the future. 

In [78]:
X_test_sc = sc.transform(df_test1)

In [79]:
# Check our target data
X_test_sc

array([[-1.21822873, -0.99803936, -0.38423583, ...,  0.20024589,
         0.34116852, -0.55432289],
       [-0.33928647, -0.99803936,  0.71778089, ...,  0.20024589,
         0.44030336, -0.55432289],
       [ 0.26968045,  0.36107928, -0.27082919, ...,  0.20024589,
        -0.84844954, -0.5128261 ],
       ...,
       [-0.5524249 ,  0.36107928,  0.4589179 , ..., -3.42582829,
         0.37421346,  0.93956182],
       [-1.06801689, -2.357158  , -0.31027498, ...,  0.20024589,
        -0.68322481, -0.55432289],
       [ 1.02276954,  1.72019792, -0.10318459, ...,  0.20024589,
        -0.71626976, -0.5128261 ]])

In [80]:
# Predict the SalePrice for test data
y_test_predicted = regression.predict(X_test_sc)

In [81]:
y_test_predicted

array([[11.618853  ],
       [11.99541337],
       [12.05305616],
       ...,
       [11.87260583],
       [11.73870597],
       [12.37279009]])

In [82]:
# Create a dataframe to have a better view
data = pd.DataFrame({'Log_Price': y_test_predicted.flatten()})
data.head()

Log_Price
0      11.62
1      12.00
2      12.05
3      12.17
4      12.19

In [83]:
data.shape

(1435, 1)

In [84]:
# To identify the SalePrice, we create a number list 
ld = [i for i in range(1,1436)]

In [85]:
# The list needs to be changed to array, so they we can put it into the dataframe of SalePrice conveniently
arr = np.array(ld)

In [86]:
arr

array([   1,    2,    3, ..., 1433, 1434, 1435])

In [87]:
y_test_predicted

array([[11.618853  ],
       [11.99541337],
       [12.05305616],
       ...,
       [11.87260583],
       [11.73870597],
       [12.37279009]])

In [88]:
Price = np.exp(y_test_predicted)

In [89]:
# The dataframe we want to submiss
data_submission = pd.DataFrame({'Id': arr.flatten(), 'Price':Price.flatten()})

In [90]:
data_submission.head()

Id      Price
0   1  111174.13
1   2  162010.01
2   3  171623.12
3   4  193213.15
4   5  196527.30

Since we have used training dataset to test the model and have a 89% accuracy, we can predict SalePrice close to the real value. However, there is bias that could have impact on the regression: 

* We have selected the categorical data by histogram and box plot observation. This is subjective and could result to the removal of critical features.

* We didn't investiagte the correlation and variance of categorical data and might not have selected the most critical ones like for numerical data, whch might result to bias. 


In [91]:
# Export data
data_submission.to_csv(os.path.join(path, 'data_submission.csv'))

In [92]:
data_actual_vs_prediction_1.to_csv(os.path.join(path, 'data_actual_vs_prediction.csv'))